<script setup lang="ts">
import { computed, ref } from "vue";
import CodeMirror from "./CodeMirror.vue";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import {
  Resource,
  getAlias,
  getVersionFromPackage,
  group2Versions,
} from "./helper";

const defaultName = "KoolController";
const goVersionOptions: string[] = [
  "1.21.4",
  "1.21.3",
  "1.21.2",
  "1.21.1",
  "1.20",
  "1.19",
  "1.18",
];
const k8sApiVersionOptions: string[] = ["0.28.3", "0.28.2"];
const builtinResourcesOptions: Resource[] = [
  {
    kind: "Deployment",
    group: "apps",
    version: "v1",
    package: "k8s.io/api/apps/v1",
  },
  {
    kind: "StatefulSet",
    group: "apps",
    version: "v1",
    package: "k8s.io/api/apps/v1",
  },
  {
    kind: "ReplicaSet",
    group: "apps",
    version: "v1",
    package: "k8s.io/api/apps/v1",
  },
  {
    kind: "DaemonSet",
    group: "apps",
    version: "v1",
    package: "k8s.io/api/apps/v1",
  },

  {
    kind: "Job",
    group: "batch",
    version: "v1",
    package: "k8s.io/api/batch/v1",
  },
  {
    kind: "CronJob",
    group: "batch",
    version: "v1",
    package: "k8s.io/api/batch/v1",
  },

  {
    kind: "Binding",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
  { kind: "Pod", group: "core", version: "v1", package: "k8s.io/api/core/v1" },
  {
    kind: "PodTemplate",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
  {
    kind: "Endpoints",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
  {
    kind: "ReplicationController",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
  { kind: "Node", group: "core", version: "v1", package: "k8s.io/api/core/v1" },
  {
    kind: "Namespace",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
  {
    kind: "Service",
    group: "core",
    version: "v1",
    package: "k8s.io/api/core/v1",
  },
];

const controllerName = ref<string>(defaultName);
const lowerControllerName = computed<string>(() =>
  controllerName.value.toLowerCase()
);
const customGoModuleName = ref<boolean>(false);
const customGoModule = ref<string>(defaultName.toLowerCase());
const goModule = computed<string>(() => {
  return customGoModuleName.value
    ? customGoModule.value
    : lowerControllerName.value;
});
const goVersion = ref<string>(goVersionOptions[0]);
const k8sApiVersion = ref<string>(k8sApiVersionOptions[0]);
const retry = ref<number>(3);
const namespace = ref<string>("");

const podResource: Resource = { ...builtinResourcesOptions[7] };
const resources = ref<Resource[]>([podResource]);

const imports = computed<string[]>(() => {
  const set = new Set<string>();
  resources.value.forEach((item) => {
    if (typeof item.package === "undefined") {
      return;
    }
    if (!item.isCustomResource && item.kind.length > 0) {
      set.add(`k8s.io/api/${item.group}/${item.version}`);
      return;
    }
    item.package.length === 0 ||
      item.package === goModule.value ||
      set.add(item.package);
  });
  return Array.from(set).sort();
});

function addResource() {
  resources.value.push({ kind: "", package: "", isCustomResource: true });
  console.log(resources.value);
  console.log(imports.value);
}

function deleteResource(index: number) {
  resources.value.splice(index, 1);
}

function changeCustomGoModuleNameFlag() {
  if (customGoModuleName.value) {
    customGoModule.value = lowerControllerName.value;
  }
}

function changeKind(index: number) {
  const newItem = builtinResourcesOptions.filter(
    (i) => i.kind === resources.value[index].kind
  )[0];
  resources.value[index] = { ...newItem };
}

function resetResource(index: number) {
  resources.value[index].group = "";
  resources.value[index].version = "";
  resources.value[index].package = "";
  if (resources.value[index].isCustomResource) {
    resources.value[index].kind = "";
  }
}

function tryResetResourceVersion(index: number) {
  const v = getVersionFromPackage(resources.value[index].package);
  if (v.length > 0) {
    resources.value[index].version = v;
  }
}

// code

const _goMod = computed<string>(() => {
  return `module ${goModule.value}

go ${goVersion.value}

require (
	github.com/FlyingOnion/kool v0.0.0-20231117094958-b286212bb91c
	github.com/mitchellh/mapstructure v1.5.0
	github.com/spf13/pflag v1.0.5
	k8s.io/apimachinery v${k8sApiVersion.value}
	k8s.io/client-go v${k8sApiVersion.value}
	k8s.io/klog/v2 v2.110.1
)
`;
});
const _main = computed<string>(() => {
  return `// Code generated by koolbuilder. DO NOT EDIT.

package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/FlyingOnion/kool"
	"github.com/spf13/pflag"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/workqueue"
	"k8s.io/klog/v2"
	${imports.value.map((pkg) => `${getAlias(pkg)} "${pkg}"`).join("\n\t")}
)

func mustGetOrLogFatal[T any](v T, err error) T {
	if err != nil {
		klog.Fatal(err)
	}
	return v
}

func addKnownTypes(s *runtime.Scheme) {
${resources.value
  .filter((item) => item.isCustomResource)
  .map(
    (item) => `\ts.AddKnownTypes(schema.GroupVersion{
\t\tGroup:   "${item.group || "undefined"}",
\t\tVersion: "${item.version || "undefined"}",
\t}, &${goType(item)}{})\n`
  )
  .join("\n\t")}}

func main() {
	var kubeconfig string
	var master string

	pflag.StringVar(&kubeconfig, "kubeconfig", "", "absolute path to the kubeconfig file")
	pflag.StringVar(&master, "master", "", "master url")
	pflag.Parse()

	addKnownTypes(scheme.Scheme)

	config := mustGetOrLogFatal(clientcmd.BuildConfigFromFlags(master, kubeconfig))
	client := mustGetOrLogFatal(rest.RESTClientFor(config))

	${resources.value
    .map(
      (item) =>
        `${item.kind.toLowerCase() || "unknowntype"}Informer := kool.New${
          item.isNamespaced ? "Namespaced" : ""
        }Informer[${goType(item)}](client, 30*time.Second)`
    )
    .join("\n\t")}

	queue := workqueue.NewRateLimitingQueue(workqueue.DefaultControllerRateLimiter())
	controller := New${controllerName.value}(${resources.value.map(
    (item) => `${item.kind.toLowerCase() || "unknowntype"}Informer, `
  )}queue, ${retry.value})

	sigC := make(chan os.Signal, 1)
	signal.Notify(sigC, syscall.SIGINT, syscall.SIGTERM)

	ctx, cancel := context.WithCancel(context.Background())

	go controller.Run(ctx, 1)

	select {
	case sig := <-sigC:
		klog.Infof("Received signal: %s", sig)
		signal.Stop(sigC)
		cancel()
	case <-ctx.Done():
	}
}
`;
});
const _controller = computed<string>(() => {
  return `package main`;
});

const files: string[] = ["go.mod", "main.go", "controller.go", "custom.go"];
const currentFile = ref<string>("main.go");
const filesMap = {
  "go.mod": _goMod,
  "main.go": _main,
  "controller.go": _controller,
};
const code = computed<string>(() => {
  const r = filesMap[currentFile.value];
  return r.value || "";
});

function changeFile(file: string) {
  currentFile.value = file;
  console.log(file);
}

function goType(rs: Resource): string {
  const kind = rs.kind.length > 0 ? rs.kind : "UnknownType";
  return rs.isCustomResource &&
    (rs.package?.length === 0 || rs.package === goModule.value)
    ? kind
    : getAlias(rs.package) + "." + kind;
}

function kindDeepCopyGen(kind: string): string {
  return kind.toLowerCase() + "_gen.deepcopy.go";
}

function download() {
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file, filesMap[file].value);
  }
  // zip.file("go.mod", _goMod.value);
  // zip.file("main.go", _main.value);
  // zip.file("controller.go", _controller.value);

  zip.generateAsync({ type: "blob" }).then((content) => {
    saveAs(content, `${controllerName.value}.zip`);
  });
}
</script>

<template>
  <div flex flex-wrap gap-4 p-4>
    <div flex flex-col gap-1 min-w-100>
      <p class="text-2xl font-semibold leading-7 text-gray-900">Kool Builder</p>
      <p class="text-base leading-6 text-gray-600">
        Build your kubernetes operator easily
      </p>
      <p>(WIP)</p>
      <p class="text-xl font-semibold leading-10 text-gray-600">Basic</p>
      <div flex flex-col gap-1>
        <!-- controller name -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="controller" flex-1>Controller Name</label>
          </span>
          <span flex-1 flex>
            <input
              id="controller"
              v-model="controllerName"
              flex-grow
              border
              rounded
              px-2
            />
          </span>
        </div>
        <!-- custom go module -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="custom-go-module" flex-1>Custom Go Module</label>
          </span>
          <span flex-1 flex>
            <input
              id="custom-go-module"
              type="checkbox"
              v-model="customGoModuleName"
              @change="changeCustomGoModuleNameFlag"
            />
            <label for="custom-go-module" flex-grow></label>
          </span>
        </div>
        <!-- go module -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="go-module" flex-1>Go Module</label>
          </span>
          <span flex-1 flex>
            <input
              v-if="customGoModuleName"
              id="go-module"
              v-model="customGoModule"
              flex-grow
              border
              rounded
              px-2
            />
            <input
              v-else
              id="go-module"
              v-model="lowerControllerName"
              disabled
              flex-grow
              border
              rounded
              px-2
              disabled-bg-light
            />
          </span>
        </div>
        <!-- go version -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="go-version" flex-1>Go Version</label>
          </span>
          <span flex-1>
            <select id="go-version" v-model="goVersion" min-w-20 border rounded>
              <option
                v-for="item in goVersionOptions"
                :key="item"
                :value="item"
              >
                {{ item }}
              </option>
            </select>
          </span>
        </div>
        <!-- k8s api version -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="k8s-api-version" flex-1>Kubernetes API Version</label>
          </span>
          <span flex-1>
            <select
              id="k8s-api-version"
              v-model="k8sApiVersion"
              min-w-20
              border
              rounded
            >
              <option
                v-for="item in k8sApiVersionOptions"
                :key="item"
                :value="item"
              >
                {{ item }}
              </option>
            </select>
          </span>
        </div>
        <!-- namespace -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="namespace" flex-1>Namespace</label>
          </span>
          <span flex-1 flex>
            <input
              id="namespace"
              v-model="namespace"
              flex-grow
              border
              rounded
              px-2
            />
          </span>
        </div>
        <!-- retry -->
        <div flex>
          <span flex-1 flex max-w-80>
            <label for="retry" flex-1>Retry</label>
          </span>
          <span flex-1 flex>
            <input
              id="retry"
              type="number"
              v-model="retry"
              flex-grow
              border
              rounded
              px-2
            />
          </span>
        </div>
      </div>

      <p class="text-xl font-semibold leading-10 text-gray-600">Resources</p>
      <div flex flex-col gap-1>
        <template v-for="(item, index) in resources" :key="index">
          <!-- title and delete button -->
          <div flex>
            <span
              flex-1
              max-w-80
              text-lg
              font-400
              leading-6
              text-gray-600
              select-none
            >
              {{
                index === 0 ? "Main Resource" : "Resource " + index.toString()
              }}
            </span>
            <span flex-1 flex justify-end>
              <button
                type="button"
                @click="deleteResource(index)"
                flex
                items-center
                rounded
                px-1
                py-1
                font-sans
                text-sm
                hover:bg-gray-100
              >
                Delete
                <span i-tabler-trash></span>
              </button>
            </span>
          </div>
          <!-- custom resource -->
          <div flex>
            <span flex-1 max-w-80>
              <label :for="'custom-' + index.toString()">Custom Resource</label>
            </span>
            <span flex-1 flex>
              <input
                :id="'custom-' + index.toString()"
                type="checkbox"
                v-model="item.isCustomResource"
                @change="resetResource(index)"
              />
              <label :for="'custom-' + index.toString()" flex-grow></label>
            </span>
          </div>
          <!-- group -->
          <div flex>
            <span flex-1 max-w-80>
              <label :for="'group-' + index.toString()">Group</label>
            </span>
            <span flex-1 flex>
              <input
                :id="'group-' + index.toString()"
                v-model="item.group"
                :disabled="!item.isCustomResource"
                flex-grow
                border
                rounded
                px-2
                disabled-bg-light
              />
            </span>
          </div>
          <!-- kind -->
          <div flex>
            <span flex-1 max-w-80>
              <label :for="'kind-' + index.toString()">Kind</label>
            </span>
            <span flex-1 flex>
              <input
                v-if="item.isCustomResource"
                :id="'kind-' + index.toString()"
                v-model="item.kind"
                flex-grow
                border
                rounded
                px-2
              />
              <select
                v-else
                :id="'kind-' + index.toString()"
                v-model="item.kind"
                @change="changeKind(index)"
                flex-grow
                min-w-20
                border
                rounded
                px-1
              >
                <option
                  v-for="item in builtinResourcesOptions"
                  :key="item.kind"
                  :value="item.kind"
                >
                  {{ item.kind }}
                </option>
              </select>
            </span>
          </div>
          <!-- version -->
          <div flex>
            <span flex-1 max-w-80>
              <label :for="'version-' + index.toString()">Version</label>
            </span>
            <span v-if="item.isCustomResource" flex-1 flex>
              <input
                :id="'version-' + index.toString()"
                v-model="item.version"
                list="versionList"
                flex-grow
                border
                rounded
                px-2
              />
              <datalist id="versionList">
                <option>v1</option>
                <option>v1alpha1</option>
                <option>v1alpha2</option>
                <option>v1beta1</option>
                <option>v1beta2</option>
                <option>v2</option>
                <option>v2alpha1</option>
                <option>v2alpha2</option>
                <option>v2beta1</option>
                <option>v2beta2</option>
              </datalist>
            </span>
            <span v-else flex-1 flex>
              <select
                :id="'version-' + index.toString()"
                v-model="item.version"
                :disabled="item.kind.length === 0"
                flex-grow
                min-w-20
                border
                rounded
                px-1
                disabled-bg-light
              >
                <option
                  v-for="version in group2Versions(item.group)"
                  :key="version"
                  :value="version"
                >
                  {{ version }}
                </option>
              </select>
            </span>
          </div>
          <!-- package -->
          <div v-show="item.isCustomResource" flex>
            <span flex-1 max-w-80>
              <label :for="'package-' + index.toString()">Package</label>
            </span>
            <span flex-1 flex>
              <input
                :id="'package-' + index.toString()"
                v-model="item.package"
                @change="tryResetResourceVersion(index)"
                flex-grow
                border
                rounded
                px-2
              />
            </span>
          </div>
        </template>
        <button
          @click="addResource"
          flex
          items-center
          justify-center
          rounded
          px-1
          py-1
          font-sans
          text-sm
          hover:bg-gray-100
        >
          Add
          <span i-tabler-circle-plus></span>
        </button>
      </div>
    </div>
    <div flex-grow flex flex-col gap-1 min-w-128>
      <div flex>
        <p flex-1 text-xl font-semibold leading-10 text-gray-600>Output</p>
        <button
          @click="download"
          flex
          items-center
          justify-center
          rounded
          px-2
          py-2
          font-semibold
          text-sm
          text-gray-600
          hover:bg-gray-100
        >
          Download Zip
          <span i-tabler-download></span>
        </button>
      </div>
      <div>
        <div flex flex-col gap-1>
          <ul>
            <li v-for="f in files" :key="f">
              <a
                text-center
                rounded
                px-1
                py-1
                font-sans
                text-sm
                cursor-pointer
                hover:bg-gray-100
                role="tab"
                :aria-selected="f === currentFile"
                @click="changeFile(f)"
                >{{ f }}</a
              >
            </li>
            <li
              v-for="r in resources.filter((r) => r.genDeepCopy)"
              :key="r.kind"
            >
              <a
                text-center
                rounded
                px-1
                py-1
                font-sans
                text-sm
                cursor-pointer
                hover:bg-gray-100
                role="tab"
                :aria-selected="kindDeepCopyGen(r.kind) === currentFile"
                @click="changeFile(kindDeepCopyGen(r.kind))"
                >{{ kindDeepCopyGen(r.kind) }}</a
              >
            </li>
          </ul>
          <code-mirror :code="code"></code-mirror>
        </div>
      </div>
    </div>
  </div>
</template>
